asudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t madhu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true madhu/react-test npm test

after_success:
  - docker build -t madhu/multi-client ./client
  - docker build -t madhu/multi-nginx ./nginx
  - docker build -t madhu/multi-server ./server
  - docker build -t madhu/multi-worker ./worker
  # Log in to the docker CLI
  # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io

  # Tag the images with docker username prefix
  - docker tag madhu/multi-client dockerjhili/multi-client
  - docker tag madhu/multi-nginx dockerjhili/multi-nginx
  - docker tag madhu/multi-server dockerjhili/multi-server
  - docker tag madhu/multi-worker dockerjhili/multi-worker

  # Take those images and push them to docker hub
  - docker push dockerjhili/multi-client
  - docker push dockerjhili/multi-nginx
  - docker push dockerjhili/multi-server
  - docker push dockerjhili/multi-worker
