sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t madhu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run madhu/react-test npm run test -- --coverage

after_success:
  - docker build -t madhu/multi-client ./client
  - docker build -t madhu/multi-nginx ./nginx
  - docker build -t madhu/multi-server ./server
  - docker build -t madhu/multi-worker ./worker

  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub

  - docker push madhu/multi-client
  - docker push madhu/multi-nginx
  - docker push madhu/multi-server
  - docker push madhu/multi-worker